### ISSUE TITLE
Question is still marked as solved when the correct answer is removed

### ISSUE THREAD

**Issue by mateimarica** [mateimarica/qrequest#3]
Note the checkmark and the "0 responses"

![image](https://user-images.githubusercontent.com/19232017/103417155-f0459380-4b5f-11eb-8e0b-45002a41eb74.png)

Potential fixes (one or the other):

-  Checking if the answer being deleted is the correct answer to its question
- Making it so that when a correct answer is deleted, it's then marked as "anonymous" and the answer's author's name disappears but the answer still stays up.

**Comment by chrismacarthur** [comment]
Bug has seemingly been fixed and pull request has been sent. Let me know if any revisions, changes, or corrections must be made!
